### ISSUE TITLE
Default break "width" can exceed video duration

### ISSUE THREAD

**Issue by mostolog** [polimediaupv/paella-opencast#34]
Hi
Using latest paella editor (ie: this repo branch), when editing a short video (1min), adding a break event on editor creates a blue layer which seems to have a default minimum length (1min?) that exceeds the video end, which seem to make impossible to shrink it.

**Comment by miesgre** [comment]
@mostolog This seems to be a issue in the polimediaupv/paella-editor project. 

I'm closing this issue as I created a new one in paella-editor project (polimediaupv/paella-editor#3)
