### ISSUE TITLE
When does paella-opencast get a new paella version?

### ISSUE THREAD

**Issue by doofy** [polimediaupv/paella-opencast#39]
I'm asking about you update policy of paella-opencast. At this moment paella-opencast is on 5.2.10. There is a new patch version for paella 5.2.11 already released. Further there is already a paella 5.3.3 release. When does paella-opencast get updated?

**Comment by miesgre** [comment]
Hi @doofy. I updated paella-opencast to paella 5.2.13 (https://github.com/polimediaupv/paella-opencast/releases/tag/5.2.13).

Paella is now integrated into opencast (https://github.com/opencast/opencast/pull/15). Opencast 5.x will have paella as a (optional) player (https://github.com/opencast/opencast/tree/r/5.x/modules/engage-paella-player).

As paella bundle is now in opencast tree, we does not plan to maintain this module anymore. All paella opencast bundle development will be in opencast github repository (https://github.com/opencast/opencast).

We are working in update the opencast module to use paella 5.3 (https://opencast.jira.com/browse/MH-12800) and we will make a pull request in a few days.

**Comment by doofy** [comment]
@miesgre opencast 5 is scheduled to be released on June 12th this year. Many institutions updated to Opencast 4 and plan to stay there for a while. They cannot update to opencast 5 to get a new paella version. I would like you to reconsider your plan to stop maintaining paella and paella-opencast. At least until there is a release version of opencast that includes paella.

**Comment by miesgre** [comment]
@doofy You are right. We can update this bundle with paella 5.3
