### ISSUE TITLE
Audio-Transcript Download Option

### ISSUE THREAD

**Issue by rrolf** [polimediaupv/paella-opencast#56]
It would be great if captions could be downloaded as a text file with the audio transcript. 

Paella already displays the text as a regular text in the captions dialog, but it would be copy paste or some thing like this to get a text file. 

It would be nicer to have a file to download that has not the time stamps of the captions file but maybe the metadata of the recording and the URL of the event.

**Comment by miesgre** [comment]
Fixed in https://github.com/opencast/opencast/pull/5532
